---
name: Build and Lint
on:
  - push
  - pull_request
jobs:
  build:
    uses: jabrown93/.github/.github/workflows/node-build.yml@644b89511f2e5143fb600246050eaf3aa5f532eb # v1.5.0
    with:
      node-versions: '["22.x", "24.x"]'
