---
name: Release
on:
  push:
    branches:
      - main
      - beta
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false
jobs:
  release:
    uses: jabrown93/.github/.github/workflows/npm-release.yml@646fa5ec406b9d4ee20498512d6748135f4a6206 # v1.1.0
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
