---
name: Release
on:
  push:
    branches:
      - main
      - beta
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false
jobs:
  release:
    uses: jabrown93/.github/.github/workflows/npm-release.yml@71c3af9fc09ce87b086cc058773380acaf2b1299 # v1.2.0
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
