---
name: Release
on:
  push:
    branches:
      - main
      - beta
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false
jobs:
  release:
    uses: jabrown93/.github/.github/workflows/npm-release.yml@0bf454f053aea7af353980597006ec03b3ca9870 # v1.4.0
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    secrets:
      APP_ID: ${{ secrets.APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
