---
name: SBOM release

on:
  release:
    types: [published]

jobs:
  sbom:
    uses: jabrown93/ci/.github/workflows/sbom-release.yml@b70e41bf036b757899993918c1788f38c3c472fc # workflows-v3.0.0
    permissions:
      contents: write
      id-token: write
      attestations: write
