---
name: SBOM release

on:
  release:
    types: [published]

jobs:
  sbom:
    uses: jabrown93/ci/.github/workflows/sbom-release.yml@ae4c0bc7c75c6d86853aad5dbc830dfa6607c446 # workflows-v2.1.4
    permissions:
      contents: write
      id-token: write
      attestations: write
