---
name: SBOM release

on:
  release:
    types: [published]

jobs:
  sbom:
    uses: jabrown93/ci/.github/workflows/sbom-release.yml@c8974ae4b64382b9899254f57e0d8270eb769c03 # workflows-v3.0.1
    permissions:
      contents: write
      id-token: write
      attestations: write
