---
name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *'
jobs:
  stale:
    uses: jabrown93/.github/.github/workflows/stale.yml@0bf454f053aea7af353980597006ec03b3ca9870 # v1.4.0
    permissions:
      actions: write
      issues: write
      pull-requests: write
